### ISSUE TITLE
[Dotnet] Failure to notify publish failure

### ISSUE THREAD

**Issue by guineveresaenger** [pulumi/pulumi-package-publisher#20]
On Nov 3, 2023, our Nuget Registry token expired.

All publish jobs to Nuget started failing. ([example](https://github.com/pulumi/pulumi-akamai/actions/runs/6780270868/job/18428852231#step:3:2148))

We received no notifications of this failure. This was discovered during [GCP upgrade tests](https://github.com/pulumi/templates/actions/runs/6802393224/job/18495394348#step:21:1276).

When any publish step fails, we should:

- notify the team of the publish failure
- fail the publish job 
  - since we publish to multiple registries, a conversation should be had on whether we would continue publishing to the other registries even if one registry was unsuccessful.

**Comment by ericrudder** [comment]
@Guinevere Saenger ***@***.***> does the new token have an
expiration date?  i think @Keith Mosher ***@***.***> was trying to
put together a calendar of "critical events" like this that we could review
at the beginning of each milestone ...

**Comment by iwahbe** [comment]
>When any publish step fails, we should:
>
> - notify the team of the publish failure
> - fail the publish job

If we fail the publish job, that should be sufficient to notify the team, since that should create a P1 on the failure. We should confirm the P1 gets created, but my understanding of our existing automation is that it will.

>   - since we publish to multiple registries, a conversation should be had on whether we would continue publishing to the other registries even if one registry was unsuccessful.

Since publishing isn't atomic across registries, we need to be prepared for a world where one registry is published to, and another is not. Given that, I think we should publish to all registries, even if a publish is not successful. We will need to be able to run targeted publish jobs anyway.

**Comment by guineveresaenger** [comment]
@ericrudder I will follow up with @kmosher on Slack. Nuget tokens expire after 1 year.

**Comment by guineveresaenger** [comment]
@iwahbe that wasn't quite what I was trying to say - I was trying to say that if one publish step fails, the "following" (i.e. other registry) steps should still proceed (I think we agree here) but there's a few ways of how GHA handles that, and we need to make sure that whichever way we choose does indeed result in reporting an overall failure.

Currently, the publishing steps are idempotent - each publishing tool verifies first whether such a package exists, and no-ops if it already does.

**Comment by VenelinMartinov** [comment]
Lovely, the GHA logs for the originally reported failure are lost.

Would appreciate some more recent examples of this happening as otherwise we're down to guessing how that happened.

**Comment by VenelinMartinov** [comment]
Reproed in https://github.com/pulumi/pulumi-random/actions/runs/9351576998/job/25738106072
