### ISSUE TITLE
New release including #42

### ISSUE THREAD

**Issue by ringods** [pulumi/pulumi-package-publisher#44]
@danielrbradley can you make a new release of this GH action which includes #42 and use this in `ci-mgmt`?

Current `ci-mgmt` points to v0.0.20 which doesn't include the more liberal Nuget package naming. All the Pulumiverse providers where I adopted `ci-mgmt` haven't got any Nuget package release since adoption, but the publishing didn't fail. One of the users signalled this to me:

https://github.com/pulumiverse/pulumi-grafana/issues/213

**Comment by robesite** [comment]
@ringods when should we expect the new versions in [nuget](https://www.nuget.org/packages/Pulumiverse.Grafana)
